name: repropack
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - python=3.9.0
  - r-base=4.0.3
  - r-here=0.1
  - r-knitr=1.30
  - r-markdown=1.1
  - r-rmarkdown=2.5
  - r-tidyverse=1.3.0
  - snakemake=5.26.1
